package com.example.demo.admin.user.mapper;

import com.example.demo.admin.user.model.UserLogin;
import com.example.demo.admin.user.model.UserLoginExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
@Mapper
public interface UserLoginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mx_user_login
     *
     * @mbggenerated Sat May 16 17:42:58 CST 2020
     */
    int countByExample(UserLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mx_user_login
     *
     * @mbggenerated Sat May 16 17:42:58 CST 2020
     */
    int deleteByExample(UserLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mx_user_login
     *
     * @mbggenerated Sat May 16 17:42:58 CST 2020
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mx_user_login
     *
     * @mbggenerated Sat May 16 17:42:58 CST 2020
     */
    int insert(UserLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mx_user_login
     *
     * @mbggenerated Sat May 16 17:42:58 CST 2020
     */
    int insertSelective(UserLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mx_user_login
     *
     * @mbggenerated Sat May 16 17:42:58 CST 2020
     */
    List<UserLogin> selectByExampleWithRowbounds(UserLoginExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mx_user_login
     *
     * @mbggenerated Sat May 16 17:42:58 CST 2020
     */
    List<UserLogin> selectByExample(UserLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mx_user_login
     *
     * @mbggenerated Sat May 16 17:42:58 CST 2020
     */
    UserLogin selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mx_user_login
     *
     * @mbggenerated Sat May 16 17:42:58 CST 2020
     */
    int updateByExampleSelective(@Param("record") UserLogin record, @Param("example") UserLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mx_user_login
     *
     * @mbggenerated Sat May 16 17:42:58 CST 2020
     */
    int updateByExample(@Param("record") UserLogin record, @Param("example") UserLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mx_user_login
     *
     * @mbggenerated Sat May 16 17:42:58 CST 2020
     */
    int updateByPrimaryKeySelective(UserLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mx_user_login
     *
     * @mbggenerated Sat May 16 17:42:58 CST 2020
     */
    int updateByPrimaryKey(UserLogin record);
}